/* B1611840 (NEW-1) — a road/pad or road/road junction's DISSOLVED pavement ring can carry a
 * spurious near-duplicate vertex right at a curb-return tangent point. Two pieces generated by
 * different code paths (a tessellated strip, an analytically solved fillet wedge) rarely land on
 * exactly the same point, and the morphological close that bridges the sub-inch gap between them
 * (`dissolveRings`'s own `closePaths`) — or the defensive convex-hull fallback in `teeGeometry`'s
 * wedge builder — can itself introduce a short "in and out" detour of a few hundredths to a couple
 * of feet. Sub-inch, no enclosed unpaved area, nothing visible today — but the same species of
 * numerical noise that has already grown into a visible thin paved spike once before, when a later
 * change nudged the geometry enough to expose it. Clean the ring rather than wait for a repeat.
 *
 * This suite is the RED-PROOF the item asked for: every scenario below reproduces on unmodified
 * `origin/main` as a turn-angle spike riding a short segment — measured directly (see the dispatch
 * session's own diagnostic sweep), not assumed — before any fix was written.
 *
 * The assertion is a SELF-CONTAINED turn-angle scan, deliberately NOT importing the fix's own
 * `ringSpikes`/`collapseRingSpikes` helpers — this instrument has to be able to convict the
 * UNFIXED geometry on its own terms, the same way `roadDriveJunctionFillet.test.js` keeps its own
 * local `isSimplePolygon` rather than trusting the library under test.
 */
import { describe, it, expect } from "vitest";
import { rectEdges, nearestRectEdge, teeGeometry, nodeJunction } from "../src/workspaces/site-planner/lib/roadGeometry.js";
import { dissolveRings } from "../src/workspaces/site-planner/lib/roadNetwork.js";
import { roadStripRing, roadCurbWidth } from "../src/workspaces/site-planner/lib/siteGeometry.js";

// A "sane bound": no genuine corner in this geometry both turns this sharply AND rides a segment
// this short. A smoothly tessellated fillet arc (DEFAULT_TESS_DEG per vertex) never turns anywhere
// near this much per vertex, however short its chords get at a tight radius — so this can never
// convict real curvature. Every genuine sharp corner here (a road's own flat end cap, the mouth
// chord where two curb returns meet near-perpendicular) sits on a segment at least a couple of feet
// long — well above SHORT_SEG_FT.
const TURN_BOUND_DEG = 100;
const SHORT_SEG_FT = 2.0;

function ringTurnSpikes(ring, turnBoundDeg, shortSegFt) {
  const n = ring.length;
  const out = [];
  for (let i = 0; i < n; i++) {
    const a = ring[(i - 1 + n) % n], b = ring[i], c = ring[(i + 1) % n];
    const v1 = { x: b.x - a.x, y: b.y - a.y }, v2 = { x: c.x - b.x, y: c.y - b.y };
    const len1 = Math.hypot(v1.x, v1.y), len2 = Math.hypot(v2.x, v2.y);
    if (!(len1 > 1e-9) || !(len2 > 1e-9)) continue;
    const turnDeg = Math.abs(Math.atan2(v1.x * v2.y - v1.y * v2.x, v1.x * v2.x + v1.y * v2.y)) * 180 / Math.PI;
    if (turnDeg > turnBoundDeg && (len1 < shortSegFt || len2 < shortSegFt)) {
      out.push({ i, turnDeg: Math.round(turnDeg * 10) / 10, len1: Math.round(len1 * 1000) / 1000, len2: Math.round(len2 * 1000) / 1000 });
    }
  }
  return out;
}

function assertNoTangentSpikes(dissolved, label) {
  for (const region of dissolved) {
    const spikes = ringTurnSpikes(region.outer, TURN_BOUND_DEG, SHORT_SEG_FT);
    expect(spikes, `${label}: outer ring carries a turn-angle spike at a tangent point — ${JSON.stringify(spikes)}`).toEqual([]);
    for (const hole of region.holes || []) {
      const hspikes = ringTurnSpikes(hole, TURN_BOUND_DEG, SHORT_SEG_FT);
      expect(hspikes, `${label}: hole ring carries a turn-angle spike — ${JSON.stringify(hspikes)}`).toEqual([]);
    }
  }
}

const roadOuterHalf = (el) => Math.max(0, (+el.travelW || 0) / 2) + roadCurbWidth(el);

// Road -> paving-pad junction scenario — same construction as roadDriveJunctionFillet.test.js's own
// driveJunctionScenario (the real pipeline: rectEdges/nearestRectEdge/teeGeometry/roadStripRing/
// dissolveRings), reproduced here rather than imported so this file stays a standalone instrument.
function driveJunctionScenario(angleDeg, opts = {}) {
  const { padW = 200, padH = 150, width = 36, driveLen = 300, alongEdge = 0, edge = "bottom", R = 24, flare = 0, curb = 0.5 } = opts;
  const pad = { cx: 0, cy: 0, w: padW, h: padH, rot: 0 };
  const edges = rectEdges(pad.cx, pad.cy, pad.w, pad.h, 0);
  const edgeIdx = { bottom: 0, right: 1, top: 2, left: 3 }[edge];
  const e = edges[edgeIdx];
  const P = { x: e.mid.x + e.dir.x * alongEdge, y: e.mid.y + e.dir.y * alongEdge };
  const rad = (angleDeg * Math.PI) / 180;
  const c = Math.cos(rad), s = Math.sin(rad);
  const dir = { x: e.outN.x * c + e.dir.x * s, y: e.outN.y * c + e.dir.y * s };
  const far = { x: P.x + dir.x * driveLen, y: P.y + dir.y * driveLen };
  const road = { type: "road", pts: [far, P], vtx: [{}, {}], travelW: width, curb, roadClass: "aisle" };
  const hit = nearestRectEdge(P, edges, { facingOnly: false });
  const sideDir = { x: far.x - P.x, y: far.y - P.y };
  const edgeRunPos = (hit.edge.b.x - P.x) * hit.edge.dir.x + (hit.edge.b.y - P.y) * hit.edge.dir.y;
  const edgeRunNeg = (P.x - hit.edge.a.x) * hit.edge.dir.x + (P.y - hit.edge.a.y) * hit.edge.dir.y;
  const geom = teeGeometry({
    T: P, throughDir: hit.edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(R, Math.max(1, padH)), flare, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail: driveLen - 1,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

// Road -> road tee scenario (mirrors test/nodeJunction.test.js's own arm() helper).
const deg = (d) => ({ x: Math.cos((d * Math.PI) / 180), y: Math.sin((d * Math.PI) / 180) });
function nodeJunctionScenario(sideDeg, opts = {}) {
  const { throughW = 36, sideW = 24, R = 24 } = opts;
  const N = { x: 0, y: 0 };
  const eastEnd = { x: 300, y: 0 }, westEnd = { x: -300, y: 0 };
  const sideFar = { x: Math.cos((sideDeg * Math.PI) / 180) * 300, y: Math.sin((sideDeg * Math.PI) / 180) * 300 };
  const roadThrough = { type: "road", pts: [westEnd, eastEnd], vtx: [{}, {}], travelW: throughW, curb: 0.5, roadClass: "aisle" };
  const roadSide = { type: "road", pts: [N, sideFar], vtx: [{}, {}], travelW: sideW, curb: 0.5, roadClass: "aisle" };
  const stripThrough = roadStripRing(roadThrough, {}, new Set(), undefined);
  const stripSide = roadStripRing(roadSide, {}, new Set(), undefined);
  const arm = (dir, half, extra = {}) => ({ dir, half, avail: 400, road: "G", ...extra });
  const arms = [arm(deg(180), throughW / 2 + 0.5), arm(deg(0), throughW / 2 + 0.5), arm(deg(sideDeg), sideW / 2 + 0.5, { road: "S" })];
  const nj = nodeJunction({ node: N, arms, R });
  const wedges = (nj && nj.wedges) || [];
  return dissolveRings([stripThrough, stripSide, ...wedges]);
}

describe("NEW-1 (B1611840) — dissolved junction rings carry no degenerate tangent-point micro-segments", () => {
  it("road -> paving-pad: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const a of [0, 5, 15, 30, 45, 60, 70, 75, 80, 85, 89]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 36, R: 24, padW: 200, padH: 150 }), `pad angle ${a}`);
    }
  });

  it("road -> paving-pad: generic parking-scale pad is free of spikes too", () => {
    for (const a of [15, 45, 75]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 24, R: 15 }), `parking pad angle ${a}`);
    }
  });

  it("road -> road tee: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const sideDeg of [90, 80, 60, 45, 30, 15, 100, 120]) {
      assertNoTangentSpikes(nodeJunctionScenario(sideDeg), `road tee side=${sideDeg}deg`);
    }
  });
});
