/* B1611840 (NEW-1) — a road/pad or road/road junction's DISSOLVED pavement ring can carry a
 * spurious near-duplicate vertex right at a curb-return tangent point. Two pieces generated by
 * different code paths (a tessellated strip, an analytically solved fillet wedge) rarely land on
 * exactly the same point, and the morphological close that bridges the sub-inch gap between them
 * (`dissolveRings`'s own `closePaths`) — or the defensive convex-hull fallback in `teeGeometry`'s
 * wedge builder — can itself introduce a short "in and out" detour of a few hundredths to a couple
 * of feet. Sub-inch, no enclosed unpaved area, nothing visible today — but the same species of
 * numerical noise that has already grown into a visible thin paved spike once before, when a later
 * change nudged the geometry enough to expose it. Clean the ring rather than wait for a repeat.
 *
 * This suite is the RED-PROOF the item asked for: every scenario below reproduces on unmodified
 * `origin/main` as a turn-angle spike riding a short segment — measured directly (see the dispatch
 * session's own diagnostic sweep), not assumed — before any fix was written.
 *
 * The assertion is a SELF-CONTAINED turn-angle scan, deliberately NOT importing the fix's own
 * `ringSpikes`/`collapseRingSpikes` helpers — this instrument has to be able to convict the
 * UNFIXED geometry on its own terms, the same way `roadDriveJunctionFillet.test.js` keeps its own
 * local `isSimplePolygon` rather than trusting the library under test.
 */
import { describe, it, expect } from "vitest";
import { rectEdges, polygonEdges, nearestRectEdge, teeGeometry, nodeJunction, roadEdgeCrossing, rectContainsPoint } from "../src/workspaces/site-planner/lib/roadGeometry.js";
import { dissolveRings } from "../src/workspaces/site-planner/lib/roadNetwork.js";
import { roadStripRing, roadCurbWidth } from "../src/workspaces/site-planner/lib/siteGeometry.js";

// A "sane bound": no genuine corner in this geometry both turns this sharply AND rides a segment
// this short. A smoothly tessellated fillet arc (DEFAULT_TESS_DEG per vertex) never turns anywhere
// near this much per vertex, however short its chords get at a tight radius — so this can never
// convict real curvature. Every genuine sharp corner here (a road's own flat end cap, the mouth
// chord where two curb returns meet near-perpendicular) sits on a segment at least a couple of feet
// long — well above SHORT_SEG_FT.
const TURN_BOUND_DEG = 100;
const SHORT_SEG_FT = 2.0;

function ringTurnSpikes(ring, turnBoundDeg, shortSegFt) {
  const n = ring.length;
  const out = [];
  for (let i = 0; i < n; i++) {
    const a = ring[(i - 1 + n) % n], b = ring[i], c = ring[(i + 1) % n];
    const v1 = { x: b.x - a.x, y: b.y - a.y }, v2 = { x: c.x - b.x, y: c.y - b.y };
    const len1 = Math.hypot(v1.x, v1.y), len2 = Math.hypot(v2.x, v2.y);
    if (!(len1 > 1e-9) || !(len2 > 1e-9)) continue;
    const turnDeg = Math.abs(Math.atan2(v1.x * v2.y - v1.y * v2.x, v1.x * v2.x + v1.y * v2.y)) * 180 / Math.PI;
    if (turnDeg > turnBoundDeg && (len1 < shortSegFt || len2 < shortSegFt)) {
      out.push({ i, turnDeg: Math.round(turnDeg * 10) / 10, len1: Math.round(len1 * 1000) / 1000, len2: Math.round(len2 * 1000) / 1000 });
    }
  }
  return out;
}

function assertNoTangentSpikes(dissolved, label, turnBoundDeg = TURN_BOUND_DEG, shortSegFt = SHORT_SEG_FT) {
  for (const region of dissolved) {
    const spikes = ringTurnSpikes(region.outer, turnBoundDeg, shortSegFt);
    expect(spikes, `${label}: outer ring carries a turn-angle spike at a tangent point — ${JSON.stringify(spikes)}`).toEqual([]);
    for (const hole of region.holes || []) {
      const hspikes = ringTurnSpikes(hole, turnBoundDeg, shortSegFt);
      expect(hspikes, `${label}: hole ring carries a turn-angle spike — ${JSON.stringify(hspikes)}`).toEqual([]);
    }
  }
}

const roadOuterHalf = (el) => Math.max(0, (+el.travelW || 0) / 2) + roadCurbWidth(el);

// Road -> paving-pad junction scenario — same construction as roadDriveJunctionFillet.test.js's own
// driveJunctionScenario (the real pipeline: rectEdges/nearestRectEdge/teeGeometry/roadStripRing/
// dissolveRings), reproduced here rather than imported so this file stays a standalone instrument.
function driveJunctionScenario(angleDeg, opts = {}) {
  const { padW = 200, padH = 150, width = 36, driveLen = 300, alongEdge = 0, edge = "bottom", R = 24, flare = 0, curb = 0.5 } = opts;
  const pad = { cx: 0, cy: 0, w: padW, h: padH, rot: 0 };
  const edges = rectEdges(pad.cx, pad.cy, pad.w, pad.h, 0);
  const edgeIdx = { bottom: 0, right: 1, top: 2, left: 3 }[edge];
  const e = edges[edgeIdx];
  const P = { x: e.mid.x + e.dir.x * alongEdge, y: e.mid.y + e.dir.y * alongEdge };
  const rad = (angleDeg * Math.PI) / 180;
  const c = Math.cos(rad), s = Math.sin(rad);
  const dir = { x: e.outN.x * c + e.dir.x * s, y: e.outN.y * c + e.dir.y * s };
  const far = { x: P.x + dir.x * driveLen, y: P.y + dir.y * driveLen };
  const road = { type: "road", pts: [far, P], vtx: [{}, {}], travelW: width, curb, roadClass: "aisle" };
  const hit = nearestRectEdge(P, edges, { facingOnly: false });
  const sideDir = { x: far.x - P.x, y: far.y - P.y };
  const edgeRunPos = (hit.edge.b.x - P.x) * hit.edge.dir.x + (hit.edge.b.y - P.y) * hit.edge.dir.y;
  const edgeRunNeg = (P.x - hit.edge.a.x) * hit.edge.dir.x + (P.y - hit.edge.a.y) * hit.edge.dir.y;
  const geom = teeGeometry({
    T: P, throughDir: hit.edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(R, Math.max(1, padH)), flare, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail: driveLen - 1,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

// Road -> road tee scenario (mirrors test/nodeJunction.test.js's own arm() helper).
const deg = (d) => ({ x: Math.cos((d * Math.PI) / 180), y: Math.sin((d * Math.PI) / 180) });
function nodeJunctionScenario(sideDeg, opts = {}) {
  const { throughW = 36, sideW = 24, R = 24 } = opts;
  const N = { x: 0, y: 0 };
  const eastEnd = { x: 300, y: 0 }, westEnd = { x: -300, y: 0 };
  const sideFar = { x: Math.cos((sideDeg * Math.PI) / 180) * 300, y: Math.sin((sideDeg * Math.PI) / 180) * 300 };
  const roadThrough = { type: "road", pts: [westEnd, eastEnd], vtx: [{}, {}], travelW: throughW, curb: 0.5, roadClass: "aisle" };
  const roadSide = { type: "road", pts: [N, sideFar], vtx: [{}, {}], travelW: sideW, curb: 0.5, roadClass: "aisle" };
  const stripThrough = roadStripRing(roadThrough, {}, new Set(), undefined);
  const stripSide = roadStripRing(roadSide, {}, new Set(), undefined);
  const arm = (dir, half, extra = {}) => ({ dir, half, avail: 400, road: "G", ...extra });
  const arms = [arm(deg(180), throughW / 2 + 0.5), arm(deg(0), throughW / 2 + 0.5), arm(deg(sideDeg), sideW / 2 + 0.5, { road: "S" })];
  const nj = nodeJunction({ node: N, arms, R });
  const wedges = (nj && nj.wedges) || [];
  return dissolveRings([stripThrough, stripSide, ...wedges]);
}

describe("NEW-1 (B1611840) — dissolved junction rings carry no degenerate tangent-point micro-segments", () => {
  it("road -> paving-pad: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const a of [0, 5, 15, 30, 45, 60, 70, 75, 80, 85, 89]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 36, R: 24, padW: 200, padH: 150 }), `pad angle ${a}`);
    }
  });

  it("road -> paving-pad: generic parking-scale pad is free of spikes too", () => {
    for (const a of [15, 45, 75]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 24, R: 15 }), `parking pad angle ${a}`);
    }
  });

  it("road -> road tee: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const sideDeg of [90, 80, 60, 45, 30, 15, 100, 120]) {
      assertNoTangentSpikes(nodeJunctionScenario(sideDeg), `road tee side=${sideDeg}deg`);
    }
  });
});

/* NEW-1 (B1690816) — the sweep above used the SAME 100° bound as production's own `RING_SPIKE_TURN_DEG`,
 * so it could never see a spike that rides UNDER that bound. Measured live on deployed build 9164d24: an
 * oblique road-into-pad junction still carries two spurious vertices 0.04–0.05 ft apart, each turning
 * ~82–88° — comfortably under the old 100° bound. This is the RED-PROOF for that miss: a fine-grained
 * (0.1°) sweep, using a TIGHTER, still-independent 60° bound (above the one real ceiling a tessellated
 * arc vertex can reach — DEFAULT_TESS_DEG=6° in roadGeometry.js — and below every measured defect here),
 * across every adjacent case the item named. Confirmed RED against unmodified `origin/main` (9164d24)
 * before any fix was written; confirmed GREEN after `RING_SPIKE_TURN_DEG` moved to `DEFAULT_TESS_DEG * 5`. */
const TIGHT_TURN_BOUND_DEG = 60;

// Free-drawn POLYGON pad target (B1664512's own target kind) — an irregular, non-axis-aligned hexagon,
// so `polygonEdges`' own edge list (not `rectEdges`') is what's under test.
function polygonDriveJunctionScenario(angleDeg, opts = {}) {
  const { width = 36, driveLen = 300, R = 24 } = opts;
  const points = [
    { x: -120, y: -75 }, { x: 40, y: -95 }, { x: 130, y: -40 },
    { x: 110, y: 80 }, { x: -30, y: 100 }, { x: -140, y: 30 },
  ];
  const edges = polygonEdges(points);
  const e = edges[0];
  const P = { x: e.mid.x, y: e.mid.y };
  const rad = (angleDeg * Math.PI) / 180;
  const c = Math.cos(rad), s = Math.sin(rad);
  const dir = { x: e.outN.x * c + e.dir.x * s, y: e.outN.y * c + e.dir.y * s };
  const far = { x: P.x + dir.x * driveLen, y: P.y + dir.y * driveLen };
  const road = { type: "road", pts: [far, P], vtx: [{}, {}], travelW: width, curb: 0.5, roadClass: "aisle" };
  const hit = nearestRectEdge(P, edges, { facingOnly: false });
  const sideDir = { x: far.x - P.x, y: far.y - P.y };
  const edgeRunPos = (hit.edge.b.x - P.x) * hit.edge.dir.x + (hit.edge.b.y - P.y) * hit.edge.dir.y;
  const edgeRunNeg = (P.x - hit.edge.a.x) * hit.edge.dir.x + (P.y - hit.edge.a.y) * hit.edge.dir.y;
  const geom = teeGeometry({
    T: P, throughDir: hit.edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(R, 60), flare: 0, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail: driveLen - 1,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

// A road ending well INSIDE a pad (not near its edge) — mirrors roadDeepEndpointJunction.test.js's own
// buildRoadIntoPad, but sweeping the APPROACH ANGLE finely (that suite only ever swept insideDist).
function deepInsidePadScenario(angleDeg, insideDist, opts = {}) {
  const { padW = 400, padH = 600, width = 36, outsideLen = 100 } = opts;
  const pad = { cx: 0, cy: 0, w: padW, h: padH, rot: 0 };
  const edges = rectEdges(pad.cx, pad.cy, pad.w, pad.h, 0);
  const edgeY = -padH / 2;
  const rad = (angleDeg * Math.PI) / 180;
  const dir = { x: Math.sin(rad), y: Math.cos(rad) };
  const outside = { x: -dir.x * outsideLen, y: edgeY - dir.y * outsideLen };
  const P = { x: dir.x * insideDist, y: edgeY + dir.y * insideDist };
  const road = { type: "road", pts: [outside, P], vtx: [{}, {}], travelW: width, curb: 0.5, roadClass: "aisle" };
  const h = nearestRectEdge(P, edges, { facingOnly: false });
  const contains = rectContainsPoint(P, edges);
  if (!h || !(h.dist <= 6 || contains)) return [];
  const crossing = roadEdgeCrossing(outside, P, edges);
  const edge = crossing ? crossing.edge : h.edge;
  const pt = crossing ? crossing.pt : P;
  const insideRunFt = Math.hypot(P.x - pt.x, P.y - pt.y);
  const sideAvail = Math.max(0, Math.hypot(outside.x - P.x, outside.y - P.y) - insideRunFt);
  const sideDir = { x: road.pts[0].x - road.pts[1].x, y: road.pts[0].y - road.pts[1].y };
  const edgeRunPos = (edge.b.x - pt.x) * edge.dir.x + (edge.b.y - pt.y) * edge.dir.y;
  const edgeRunNeg = (pt.x - edge.a.x) * edge.dir.x + (pt.y - edge.a.y) * edge.dir.y;
  const perpDepth = edge.axis === "y" ? pad.h : pad.w;
  const geom = teeGeometry({
    T: pt, throughDir: edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(24, Math.max(1, perpDepth)), flare: 0, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

describe("NEW-1 (B1690816) — sub-100° tangent-point spurs collapseRingSpikes was built to remove but missed", () => {
  it("road -> paving-pad, oblique: a fine-grained sweep finds no spike above the tight bound (RED pre-fix)", () => {
    for (let a = 0; a <= 89; a += 0.5) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 36, R: 24, padW: 200, padH: 150 }), `pad angle ${a}`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("road -> paving-pad, near-perpendicular: the same fine sweep close to 90°", () => {
    for (const R of [10, 15, 24, 40]) {
      for (const width of [24, 36, 48]) {
        for (let a = 80; a <= 89.9; a += 0.5) {
          assertNoTangentSpikes(driveJunctionScenario(a, { width, R, padW: 200, padH: 150 }), `pad angle ${a} R=${R} width=${width}`, TIGHT_TURN_BOUND_DEG);
        }
      }
    }
  });

  it("road -> road tee: the same fine sweep across the oblique range", () => {
    for (let sideDeg = 5; sideDeg <= 175; sideDeg += 1) {
      assertNoTangentSpikes(nodeJunctionScenario(sideDeg), `road tee side=${sideDeg}deg`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("free-drawn POLYGON pad: the same defect class, on a non-rect target", () => {
    for (let a = 0; a <= 89; a += 0.5) {
      assertNoTangentSpikes(polygonDriveJunctionScenario(a), `polygon pad angle ${a}`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("road ending DEEP INSIDE a pad: the same defect class, at every approach angle", () => {
    for (const insideDist of [50, 150, 300]) {
      for (let a = 0; a <= 45; a += 1) {
        assertNoTangentSpikes(deepInsidePadScenario(a, insideDist), `deep-inside angle=${a} dist=${insideDist}`, TIGHT_TURN_BOUND_DEG);
      }
    }
  });
});
