/* B1611840 (NEW-1) — a road/pad or road/road junction's DISSOLVED pavement ring can carry a
 * spurious near-duplicate vertex right at a curb-return tangent point. Two pieces generated by
 * different code paths (a tessellated strip, an analytically solved fillet wedge) rarely land on
 * exactly the same point, and the morphological close that bridges the sub-inch gap between them
 * (`dissolveRings`'s own `closePaths`) — or the defensive convex-hull fallback in `teeGeometry`'s
 * wedge builder — can itself introduce a short "in and out" detour of a few hundredths to a couple
 * of feet. Sub-inch, no enclosed unpaved area, nothing visible today — but the same species of
 * numerical noise that has already grown into a visible thin paved spike once before, when a later
 * change nudged the geometry enough to expose it. Clean the ring rather than wait for a repeat.
 *
 * This suite is the RED-PROOF the item asked for: every scenario below reproduces on unmodified
 * `origin/main` as a turn-angle spike riding a short segment — measured directly (see the dispatch
 * session's own diagnostic sweep), not assumed — before any fix was written.
 *
 * The assertion is a SELF-CONTAINED turn-angle scan, deliberately NOT importing the fix's own
 * `ringSpikes`/`collapseRingSpikes` helpers — this instrument has to be able to convict the
 * UNFIXED geometry on its own terms, the same way `roadDriveJunctionFillet.test.js` keeps its own
 * local `isSimplePolygon` rather than trusting the library under test.
 */
import { describe, it, expect } from "vitest";
import { rectEdges, polygonEdges, nearestRectEdge, teeGeometry, nodeJunction, roadEdgeCrossing, rectContainsPoint } from "../src/workspaces/site-planner/lib/roadGeometry.js";
import { dissolveRings, collapseRingSpikes } from "../src/workspaces/site-planner/lib/roadNetwork.js";
import { roadStripRing, roadCurbWidth } from "../src/workspaces/site-planner/lib/siteGeometry.js";

/* ⛔ CORRECTED 2026-09-18 (B<NEW-1>/B<NEW-2>) — THIS SCANNER'S ORIGINAL PREMISE WAS FALSE, AND IT IS
 * WHY THE ACUTE-SIDE CURB-RETURN ITEM SURVIVED SIX ROUNDS AND EIGHT PRs.
 *
 * The premise it shipped with, verbatim: "no genuine corner in this geometry both turns this sharply
 * AND rides a segment this short." MEASURED on the real pipeline, that is wrong at BOTH junction
 * families, on geometry that is entirely correct:
 *   • road-into-PAD — a curb return's arc runs TANGENT into the pad edge, so the dissolved ring (which
 *     holds the road network ALONE; the pad is a separate element painted over it, Z_LAYER 1 vs 0)
 *     carries a genuine ~177 deg CUSP there. Its incoming leg is the arc's own last tessellation
 *     chord — 1.1-1.9 ft, under SHORT_SEG_FT.
 *   • road-to-ROAD tee near a through road's own END — the leftover sliver of that road's flat end cap
 *     between the return's clamped overshoot lip and the cap corner: a real 90 deg corner on a 0.3-1.1 ft leg.
 * Both were convicted as spikes, and production's `collapseRingSpikes` re-measures after each removal,
 * so removing one exposed the next arc vertex in the same cusp and the pass CASCADED — eating a
 * complete 21-point curb return down to 5 points and a straight chord across the corner. This suite
 * then reported GREEN, because the cascade had removed the very vertex it was scanning for.
 *
 * THE CORRECTION: convict only a vertex that is also REDUNDANT — one whose removal barely moves the
 * boundary. DRIFT (a vertex's distance from the straight segment joining its two neighbours) is
 * exactly "how far the ring moves if this vertex goes". The artifacts this suite was built for
 * (B1611840's near-duplicate tangent-point vertices, B1690816's 82-88 deg spurs) measured 0.04-0.05 ft
 * apart, so their drift is an order of magnitude inside the cap and they are still convicted — proven
 * directly by the teeth-proof case at the bottom of this file, which plants one and requires BOTH this
 * scanner to see it AND production to remove it. A real corner's drift is its own leg length, which is
 * why the two populations separate cleanly (0.05 ft against 1.1 ft+, with the cap at 0.25 ft between
 * them). This mirrors production's own `RING_SPIKE_DRIFT_FT`, but is derived here independently — this
 * instrument must still be able to convict the unfixed geometry on its own terms. */
const TURN_BOUND_DEG = 100;
const SHORT_SEG_FT = 2.0;
const DRIFT_FT = 0.25;

function segDist(p, a, b) {
  const vx = b.x - a.x, vy = b.y - a.y, L = vx * vx + vy * vy;
  if (!(L > 1e-12)) return Math.hypot(p.x - a.x, p.y - a.y);
  let t = ((p.x - a.x) * vx + (p.y - a.y) * vy) / L;
  t = t < 0 ? 0 : t > 1 ? 1 : t;
  return Math.hypot(p.x - (a.x + vx * t), p.y - (a.y + vy * t));
}

function ringTurnSpikes(ring, turnBoundDeg, shortSegFt, driftFt = DRIFT_FT) {
  const n = ring.length;
  const out = [];
  for (let i = 0; i < n; i++) {
    const a = ring[(i - 1 + n) % n], b = ring[i], c = ring[(i + 1) % n];
    const v1 = { x: b.x - a.x, y: b.y - a.y }, v2 = { x: c.x - b.x, y: c.y - b.y };
    const len1 = Math.hypot(v1.x, v1.y), len2 = Math.hypot(v2.x, v2.y);
    if (!(len1 > 1e-9) || !(len2 > 1e-9)) continue;
    const turnDeg = Math.abs(Math.atan2(v1.x * v2.y - v1.y * v2.x, v1.x * v2.x + v1.y * v2.y)) * 180 / Math.PI;
    const drift = segDist(b, a, c);
    if (turnDeg > turnBoundDeg && (len1 < shortSegFt || len2 < shortSegFt) && drift < driftFt) {
      out.push({ i, turnDeg: Math.round(turnDeg * 10) / 10, len1: Math.round(len1 * 1000) / 1000, len2: Math.round(len2 * 1000) / 1000, drift: Math.round(drift * 1000) / 1000 });
    }
  }
  return out;
}

function assertNoTangentSpikes(dissolved, label, turnBoundDeg = TURN_BOUND_DEG, shortSegFt = SHORT_SEG_FT) {
  for (const region of dissolved) {
    const spikes = ringTurnSpikes(region.outer, turnBoundDeg, shortSegFt);
    expect(spikes, `${label}: outer ring carries a turn-angle spike at a tangent point — ${JSON.stringify(spikes)}`).toEqual([]);
    for (const hole of region.holes || []) {
      const hspikes = ringTurnSpikes(hole, turnBoundDeg, shortSegFt);
      expect(hspikes, `${label}: hole ring carries a turn-angle spike — ${JSON.stringify(hspikes)}`).toEqual([]);
    }
  }
}

const roadOuterHalf = (el) => Math.max(0, (+el.travelW || 0) / 2) + roadCurbWidth(el);

// Road -> paving-pad junction scenario — same construction as roadDriveJunctionFillet.test.js's own
// driveJunctionScenario (the real pipeline: rectEdges/nearestRectEdge/teeGeometry/roadStripRing/
// dissolveRings), reproduced here rather than imported so this file stays a standalone instrument.
function driveJunctionScenario(angleDeg, opts = {}) {
  const { padW = 200, padH = 150, width = 36, driveLen = 300, alongEdge = 0, edge = "bottom", R = 24, flare = 0, curb = 0.5 } = opts;
  const pad = { cx: 0, cy: 0, w: padW, h: padH, rot: 0 };
  const edges = rectEdges(pad.cx, pad.cy, pad.w, pad.h, 0);
  const edgeIdx = { bottom: 0, right: 1, top: 2, left: 3 }[edge];
  const e = edges[edgeIdx];
  const P = { x: e.mid.x + e.dir.x * alongEdge, y: e.mid.y + e.dir.y * alongEdge };
  const rad = (angleDeg * Math.PI) / 180;
  const c = Math.cos(rad), s = Math.sin(rad);
  const dir = { x: e.outN.x * c + e.dir.x * s, y: e.outN.y * c + e.dir.y * s };
  const far = { x: P.x + dir.x * driveLen, y: P.y + dir.y * driveLen };
  const road = { type: "road", pts: [far, P], vtx: [{}, {}], travelW: width, curb, roadClass: "aisle" };
  const hit = nearestRectEdge(P, edges, { facingOnly: false });
  const sideDir = { x: far.x - P.x, y: far.y - P.y };
  const edgeRunPos = (hit.edge.b.x - P.x) * hit.edge.dir.x + (hit.edge.b.y - P.y) * hit.edge.dir.y;
  const edgeRunNeg = (P.x - hit.edge.a.x) * hit.edge.dir.x + (P.y - hit.edge.a.y) * hit.edge.dir.y;
  const geom = teeGeometry({
    T: P, throughDir: hit.edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(R, Math.max(1, padH)), flare, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail: driveLen - 1,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

// Road -> road tee scenario (mirrors test/nodeJunction.test.js's own arm() helper).
const deg = (d) => ({ x: Math.cos((d * Math.PI) / 180), y: Math.sin((d * Math.PI) / 180) });
function nodeJunctionScenario(sideDeg, opts = {}) {
  const { throughW = 36, sideW = 24, R = 24 } = opts;
  const N = { x: 0, y: 0 };
  const eastEnd = { x: 300, y: 0 }, westEnd = { x: -300, y: 0 };
  const sideFar = { x: Math.cos((sideDeg * Math.PI) / 180) * 300, y: Math.sin((sideDeg * Math.PI) / 180) * 300 };
  const roadThrough = { type: "road", pts: [westEnd, eastEnd], vtx: [{}, {}], travelW: throughW, curb: 0.5, roadClass: "aisle" };
  const roadSide = { type: "road", pts: [N, sideFar], vtx: [{}, {}], travelW: sideW, curb: 0.5, roadClass: "aisle" };
  const stripThrough = roadStripRing(roadThrough, {}, new Set(), undefined);
  const stripSide = roadStripRing(roadSide, {}, new Set(), undefined);
  const arm = (dir, half, extra = {}) => ({ dir, half, avail: 400, road: "G", ...extra });
  const arms = [arm(deg(180), throughW / 2 + 0.5), arm(deg(0), throughW / 2 + 0.5), arm(deg(sideDeg), sideW / 2 + 0.5, { road: "S" })];
  const nj = nodeJunction({ node: N, arms, R });
  const wedges = (nj && nj.wedges) || [];
  return dissolveRings([stripThrough, stripSide, ...wedges]);
}

describe("NEW-1 (B1611840) — dissolved junction rings carry no degenerate tangent-point micro-segments", () => {
  it("road -> paving-pad: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const a of [0, 5, 15, 30, 45, 60, 70, 75, 80, 85, 89]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 36, R: 24, padW: 200, padH: 150 }), `pad angle ${a}`);
    }
  });

  it("road -> paving-pad: generic parking-scale pad is free of spikes too", () => {
    for (const a of [15, 45, 75]) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 24, R: 15 }), `parking pad angle ${a}`);
    }
  });

  it("road -> road tee: oblique sweep is free of turn-angle spikes at the curb-return tangent points", () => {
    for (const sideDeg of [90, 80, 60, 45, 30, 15, 100, 120]) {
      assertNoTangentSpikes(nodeJunctionScenario(sideDeg), `road tee side=${sideDeg}deg`);
    }
  });
});

/* NEW-1 (B1690816) — the sweep above used the SAME 100° bound as production's own `RING_SPIKE_TURN_DEG`,
 * so it could never see a spike that rides UNDER that bound. Measured live on deployed build 9164d24: an
 * oblique road-into-pad junction still carries two spurious vertices 0.04–0.05 ft apart, each turning
 * ~82–88° — comfortably under the old 100° bound. This is the RED-PROOF for that miss: a fine-grained
 * (0.1°) sweep, using a TIGHTER, still-independent 60° bound (above the one real ceiling a tessellated
 * arc vertex can reach — DEFAULT_TESS_DEG=6° in roadGeometry.js — and below every measured defect here),
 * across every adjacent case the item named. Confirmed RED against unmodified `origin/main` (9164d24)
 * before any fix was written; confirmed GREEN after `RING_SPIKE_TURN_DEG` moved to `DEFAULT_TESS_DEG * 5`. */
const TIGHT_TURN_BOUND_DEG = 60;

// Free-drawn POLYGON pad target (B1664512's own target kind) — an irregular, non-axis-aligned hexagon,
// so `polygonEdges`' own edge list (not `rectEdges`') is what's under test.
function polygonDriveJunctionScenario(angleDeg, opts = {}) {
  const { width = 36, driveLen = 300, R = 24 } = opts;
  const points = [
    { x: -120, y: -75 }, { x: 40, y: -95 }, { x: 130, y: -40 },
    { x: 110, y: 80 }, { x: -30, y: 100 }, { x: -140, y: 30 },
  ];
  const edges = polygonEdges(points);
  const e = edges[0];
  const P = { x: e.mid.x, y: e.mid.y };
  const rad = (angleDeg * Math.PI) / 180;
  const c = Math.cos(rad), s = Math.sin(rad);
  const dir = { x: e.outN.x * c + e.dir.x * s, y: e.outN.y * c + e.dir.y * s };
  const far = { x: P.x + dir.x * driveLen, y: P.y + dir.y * driveLen };
  const road = { type: "road", pts: [far, P], vtx: [{}, {}], travelW: width, curb: 0.5, roadClass: "aisle" };
  const hit = nearestRectEdge(P, edges, { facingOnly: false });
  const sideDir = { x: far.x - P.x, y: far.y - P.y };
  const edgeRunPos = (hit.edge.b.x - P.x) * hit.edge.dir.x + (hit.edge.b.y - P.y) * hit.edge.dir.y;
  const edgeRunNeg = (P.x - hit.edge.a.x) * hit.edge.dir.x + (P.y - hit.edge.a.y) * hit.edge.dir.y;
  const geom = teeGeometry({
    T: P, throughDir: hit.edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(R, 60), flare: 0, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail: driveLen - 1,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

// A road ending well INSIDE a pad (not near its edge) — mirrors roadDeepEndpointJunction.test.js's own
// buildRoadIntoPad, but sweeping the APPROACH ANGLE finely (that suite only ever swept insideDist).
function deepInsidePadScenario(angleDeg, insideDist, opts = {}) {
  const { padW = 400, padH = 600, width = 36, outsideLen = 100 } = opts;
  const pad = { cx: 0, cy: 0, w: padW, h: padH, rot: 0 };
  const edges = rectEdges(pad.cx, pad.cy, pad.w, pad.h, 0);
  const edgeY = -padH / 2;
  const rad = (angleDeg * Math.PI) / 180;
  const dir = { x: Math.sin(rad), y: Math.cos(rad) };
  const outside = { x: -dir.x * outsideLen, y: edgeY - dir.y * outsideLen };
  const P = { x: dir.x * insideDist, y: edgeY + dir.y * insideDist };
  const road = { type: "road", pts: [outside, P], vtx: [{}, {}], travelW: width, curb: 0.5, roadClass: "aisle" };
  const h = nearestRectEdge(P, edges, { facingOnly: false });
  const contains = rectContainsPoint(P, edges);
  if (!h || !(h.dist <= 6 || contains)) return [];
  const crossing = roadEdgeCrossing(outside, P, edges);
  const edge = crossing ? crossing.edge : h.edge;
  const pt = crossing ? crossing.pt : P;
  const insideRunFt = Math.hypot(P.x - pt.x, P.y - pt.y);
  const sideAvail = Math.max(0, Math.hypot(outside.x - P.x, outside.y - P.y) - insideRunFt);
  const sideDir = { x: road.pts[0].x - road.pts[1].x, y: road.pts[0].y - road.pts[1].y };
  const edgeRunPos = (edge.b.x - pt.x) * edge.dir.x + (edge.b.y - pt.y) * edge.dir.y;
  const edgeRunNeg = (pt.x - edge.a.x) * edge.dir.x + (pt.y - edge.a.y) * edge.dir.y;
  const perpDepth = edge.axis === "y" ? pad.h : pad.w;
  const geom = teeGeometry({
    T: pt, throughDir: edge.dir, sideDir, phT: 0, phS: roadOuterHalf(road),
    R: Math.min(24, Math.max(1, perpDepth)), flare: 0, curbT: 0.5, curbS: roadCurbWidth(road),
    throughAvailPos: Math.max(0, edgeRunPos), throughAvailNeg: Math.max(0, edgeRunNeg), sideAvail,
  });
  const strip = roadStripRing(road, {}, undefined, undefined);
  const wedges = geom ? geom.wedges : [];
  return dissolveRings([strip, ...wedges]);
}

describe("NEW-1 (B1690816) — sub-100° tangent-point spurs collapseRingSpikes was built to remove but missed", () => {
  it("road -> paving-pad, oblique: a fine-grained sweep finds no spike above the tight bound (RED pre-fix)", () => {
    for (let a = 0; a <= 89; a += 0.5) {
      assertNoTangentSpikes(driveJunctionScenario(a, { width: 36, R: 24, padW: 200, padH: 150 }), `pad angle ${a}`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("road -> paving-pad, near-perpendicular: the same fine sweep close to 90°", () => {
    for (const R of [10, 15, 24, 40]) {
      for (const width of [24, 36, 48]) {
        for (let a = 80; a <= 89.9; a += 0.5) {
          assertNoTangentSpikes(driveJunctionScenario(a, { width, R, padW: 200, padH: 150 }), `pad angle ${a} R=${R} width=${width}`, TIGHT_TURN_BOUND_DEG);
        }
      }
    }
  });

  it("road -> road tee: the same fine sweep across the oblique range", () => {
    for (let sideDeg = 5; sideDeg <= 175; sideDeg += 1) {
      assertNoTangentSpikes(nodeJunctionScenario(sideDeg), `road tee side=${sideDeg}deg`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("free-drawn POLYGON pad: the same defect class, on a non-rect target", () => {
    for (let a = 0; a <= 89; a += 0.5) {
      assertNoTangentSpikes(polygonDriveJunctionScenario(a), `polygon pad angle ${a}`, TIGHT_TURN_BOUND_DEG);
    }
  });

  it("road ending DEEP INSIDE a pad: the same defect class, at every approach angle", () => {
    for (const insideDist of [50, 150, 300]) {
      for (let a = 0; a <= 45; a += 1) {
        assertNoTangentSpikes(deepInsidePadScenario(a, insideDist), `deep-inside angle=${a} dist=${insideDist}`, TIGHT_TURN_BOUND_DEG);
      }
    }
  });
});

/* TEETH PROOF for the correction above — a scanner that can no longer convict anything is not a
 * guard, it is a decoration. Plant exactly the artifact this suite was built for (a near-duplicate
 * vertex a few hundredths of a foot off a straight run, turning sharply) and require BOTH halves to
 * still work: this file's own independent scanner must SEE it, and production's `collapseRingSpikes`
 * must REMOVE it. Then plant a real curb-return cusp (a tessellated arc running tangent into a long
 * straight edge) and require the opposite of both: not convicted, not removed. */
describe("B<NEW-1> — the corrected spike scanner still convicts the junk, and no longer convicts real geometry", () => {
  // A 100 ft square with one spurious near-duplicate vertex 0.04 ft off the top edge — the B1611840 /
  // B1690816 signature, reproduced at the measured magnitude.
  const junkRing = () => [
    { x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 100 },
    { x: 50.02, y: 100.04 }, { x: 50, y: 100 },          // the spur: out 0.04 ft and straight back
    { x: 0, y: 100 },
  ];

  it("a planted 0.04 ft spur is still convicted by this file's scanner AND removed by production", () => {
    const ring = junkRing();
    const seen = ringTurnSpikes(ring, TIGHT_TURN_BOUND_DEG, SHORT_SEG_FT);
    expect(seen.length, `the scanner must still see the artifact it was built for: ${JSON.stringify(seen)}`).toBeGreaterThan(0);
    const cleaned = collapseRingSpikes(ring);
    expect(cleaned.length, "production must still remove it").toBeLessThan(ring.length);
    expect(ringTurnSpikes(cleaned, TIGHT_TURN_BOUND_DEG, SHORT_SEG_FT)).toEqual([]);
  });

  it("a real curb-return cusp (arc tangent into a long straight edge) is NOT convicted and NOT removed", () => {
    // A quarter arc of radius 15 ft tessellated at 6 deg (chords ~1.57 ft, under SHORT_SEG_FT) running
    // tangent into a 40 ft straight edge that doubles back — the exact shape the road-into-pad dissolve
    // produces, and the exact shape the old scanner convicted and the old cleanup then ate.
    const cx = 0, cy = 0, R = 15, arc = [];
    for (let d = 0; d <= 90; d += 6) {
      const t = (d * Math.PI) / 180;
      arc.push({ x: cx + R * Math.cos(t), y: cy + R * Math.sin(t) });
    }
    // close it: from the arc's last point (0, 15) straight out, and back under the arc's first point.
    const ring = [...arc, { x: -40, y: 15 }, { x: -40, y: -6 }, { x: 15, y: -6 }];
    const seen = ringTurnSpikes(ring, TIGHT_TURN_BOUND_DEG, SHORT_SEG_FT);
    expect(seen, `a tessellated arc running tangent into a straight edge is real geometry: ${JSON.stringify(seen)}`).toEqual([]);
    const cleaned = collapseRingSpikes(ring);
    expect(cleaned.length, "production must leave every arc vertex in place").toBe(ring.length);
  });

  it("CASCADE GUARD: the whole cleanup pass can never move the boundary more than its own drift cap", () => {
    // The mechanism that ate the returns: each removal is individually tiny, but the loop re-measures
    // after every one, so a chain of them walks the boundary arbitrarily far. Build a ring that offers
    // a long chain of individually-small removals and require the total movement to stay bounded.
    const R = 6, arc = [];
    for (let d = 0; d <= 180; d += 6) {
      const t = (d * Math.PI) / 180;
      arc.push({ x: R * Math.cos(t), y: R * Math.sin(t) });
    }
    const ring = [...arc, { x: -6, y: -30 }, { x: 6, y: -30 }];
    const cleaned = collapseRingSpikes(ring);
    let worst = 0;
    for (const p of ring) {
      let best = Infinity;
      for (let i = 0; i < cleaned.length; i++) best = Math.min(best, segDist(p, cleaned[i], cleaned[(i + 1) % cleaned.length]));
      worst = Math.max(worst, best);
    }
    expect(worst, `no original point may end up more than the drift cap off the cleaned ring (worst ${worst.toFixed(3)} ft)`).toBeLessThanOrEqual(0.25 + 1e-9);
  });
});
