/* Wide-zoom state / country outlines — the lazily-loaded half (NEW-1).
 *
 * ⛔ NOTHING ON THE BOOT PATH MAY STATIC-IMPORT THIS FILE. It is reached only through
 * `adminBoundaryGate.js`'s dynamic import, which fires the first time the map crosses
 * below the zoom band. The Site route's JS budget had 1.1 KB of headroom when this
 * landed (ui-audit/perf-budgets.json), so a static edge here is a CI failure, not a
 * style preference. Same rule as `exportSheet.js` (B1042) and `terrainLayers.js` (B1095).
 *
 * The geometry is a public/ asset, not a module: `public/geo/admin-boundaries.json`,
 * generated by `scripts/build-admin-boundaries.mjs` from Natural Earth 1:110m and
 * committed. Being a plain asset rather than JavaScript, it is charged against no bundle
 * budget at all, and it is requested only when this module runs — a user working at site
 * scale in Texas downloads none of it.
 *
 * CANVAS, NOT SVG. 346 rings over ~11,800 points would be 692 individually-transformed
 * SVG <path> nodes re-laid-out on every pan frame. Leaflet's canvas renderer draws the
 * whole set into one bitmap, which is the right instrument for many non-interactive
 * lines and keeps a continental pan cheap.
 *
 * SUBORDINATE BY CONSTRUCTION, three ways over:
 *   1. Its own pane at z-index 250 — above the imagery tiles (200), below the vector
 *      overlay pane (400) and every marker. Site geometry can never be occluded by it.
 *   2. `pointer-events: none` on the pane and non-interactive paths, so it cannot take a
 *      click from parcel-select, the right-click menu, or a site pin (the B98 rule).
 *   3. A white hairline over a soft dark casing — map-cartography styling that reads on
 *      both basemaps (dark aerial and light USGS topo) without matching the saturated
 *      status colours site geometry uses. Deliberately NOT app theme tokens, the same
 *      call `vectorOverlay.js` makes for its on-map lettering: this is lettering-weight
 *      furniture drawn over imagery, not app chrome.
 */
import L from "leaflet";
import { reportClientEvent } from "../../../shared/telemetry/clientErrors.js";
import { ADMIN_BOUNDARY_MAX_ZOOM } from "./adminBoundaryGate.js";
import { adminBoundaryLevels, decodeAsset } from "./adminBoundaryData.js";

const ASSET = "geo/admin-boundaries.json";
const PANE = "adminboundaries";
const PANE_Z = 250;

/* Per level: casing first, then the line over it. Weights are hairlines by intent —
 * country a touch heavier than state so the hierarchy reads without either competing. */
const STYLE = {
  country: { casing: { color: "#000", weight: 3.0, opacity: 0.28 }, line: { color: "#fff", weight: 1.2, opacity: 0.55 } },
  admin1: { casing: { color: "#000", weight: 2.2, opacity: 0.22 }, line: { color: "#fff", weight: 0.9, opacity: 0.38 } },
};

let ringsPromise = null;
function loadRings() {
  if (!ringsPromise) {
    const url = new URL(ASSET, document.baseURI).href;
    ringsPromise = fetch(url)
      .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(decodeAsset)
      .catch((e) => {
        /* LOUD-FAILURE: the map still works, so this must not throw into the finder — but
         * a boundary layer that quietly never appears is exactly the silent no-op the house
         * rule bans. Report it, and clear the cache so a later zoom-out retries. */
        ringsPromise = null;
        try { reportClientEvent("admin-boundaries-unavailable", `Wide-zoom boundary outlines could not load: ${e && e.message}`, { url }); } catch (_) { /* never let telemetry throw */ }
        throw e;
      });
  }
  return ringsPromise;
}

/* One controller per map. Holds the two level groups and swaps them in/out on zoom. */
const attached = new WeakMap();

export function attachAdminBoundaries(map) {
  if (!map) return null;
  const existing = attached.get(map);
  if (existing) return existing;

  if (!map.getPane(PANE)) {
    const pane = map.createPane(PANE);
    pane.style.zIndex = String(PANE_Z);
    pane.style.pointerEvents = "none";
  }
  const renderer = L.canvas({ pane: PANE, padding: 0.5 });
  const groups = {};
  let destroyed = false;

  const build = (rings) => {
    for (const [level, style] of Object.entries(STYLE)) {
      const group = L.layerGroup();
      for (const ring of rings[level] || []) {
        L.polyline(ring, { ...style.casing, renderer, pane: PANE, interactive: false, lineJoin: "round" }).addTo(group);
        L.polyline(ring, { ...style.line, renderer, pane: PANE, interactive: false, lineJoin: "round" }).addTo(group);
      }
      groups[level] = group;
    }
  };

  /* Add/remove whole level groups to match the gate. Leaflet skips drawing a layer that
   * is not on the map, so an out-of-band level costs nothing per frame.
   *
   * The pane is stamped with the levels currently drawn — the same trick the flood panel
   * uses with `data-surface`, and for the same reason: it gives a headless check something
   * OURS to assert against instead of reaching into Leaflet. It is a mirror of what was
   * drawn, written after the fact, never the source of truth. */
  const sync = () => {
    if (destroyed) return;
    const want = adminBoundaryLevels(map.getZoom(), ADMIN_BOUNDARY_MAX_ZOOM);
    const drawn = [];
    for (const level of Object.keys(groups)) {
      const on = map.hasLayer(groups[level]);
      if (want[level] && !on) groups[level].addTo(map);
      else if (!want[level] && on) map.removeLayer(groups[level]);
      if (want[level]) drawn.push(level);
    }
    const pane = map.getPane(PANE);
    if (pane) pane.dataset.levels = drawn.join(" ");
  };

  const controller = {
    sync,
    destroy() {
      destroyed = true;
      map.off("zoomend", sync);
      for (const g of Object.values(groups)) { try { map.removeLayer(g); } catch (_) { /* map already torn down */ } }
      attached.delete(map);
    },
  };
  attached.set(map, controller);

  loadRings().then(
    (rings) => { if (!destroyed) { build(rings); map.on("zoomend", sync); sync(); } },
    () => { attached.delete(map); }, // already reported; a later zoom-out re-attaches and retries
  );
  return controller;
}
