-- NEW-1 — PROPOSED repair for rows whose rename marker was already erased.
--
-- ⛔ SUPERSEDED 2026-09-12 (B1584832, "NEW-2") — its one repair below RAN, folded into a broader pass.
-- The 2026-09-12 review found this file's "64 rows, 1 repairable" scope was already stale: by then 88
-- of 125 rows carried no valid stamp, not 64 of 116. `rename_stamp_backfill_20260912.sql` re-derives
-- this exact one-row transcription (`sms9c5oc7jnt` → 1785525795307, still the only row any live sibling
-- can vouch for) as its Tier 1, and additionally seeds the other 87 unprotected rows from their own
-- `updated_at` (Tier 2, since no group anywhere holds a stamp for them). Read that file instead of this
-- one for current state; this file is kept only as the historical record of the original one-row finding.
--
-- ⛔ READ THIS FIRST (historical). This file was NOT executed against planyr_production on its own. The
-- dispatch that produced it said, verbatim: "propose a backfill for the 64 rows already carrying an
-- empty marker but do NOT silently rewrite the owner's data — file it and say what you would run."
-- The guard that stops the damage recurring (db/sites_rename_stamp_guard.sql) IS applied and rewrote
-- nothing; this is the separate, owner-authorised repair of what is already there.
--
-- ============================================================================================
-- WHAT IS ACTUALLY REPAIRABLE — 1 ROW, NOT 64
-- ============================================================================================
-- 64 rows carry a present-but-empty marker. That number is NOT the size of the damage, and treating
-- it as such is the mistake to avoid: for 63 of them NO row anywhere in their group carries a stamp,
-- so there is no recorded rename to restore. Writing them a timestamp would be INVENTING a fact —
-- the same class of error as showing a Colorado site a Texas-derived number. An unstamped group is
-- correctly served by `projectName.nameAuthority`'s legacy majority tier and needs nothing.
--
-- Exactly ONE row can be repaired from evidence the database already holds:
--
--   plan  sms9c5oc7jnt   group smrp1wrgg6u5 ("Silvestri")
--   its four live siblings all carry siteRenamedAt = 1785525795307 (2026-07-31T19:23:15.307Z)
--   this row carries JSON null, updated_at 2026-08-05T19:18:05Z — five days AFTER that rename
--
-- Its stamp was not missing, it was ERASED, and the value that belongs there is not a guess: it is
-- the stamp its own group unanimously holds. Restoring it is a TRANSCRIPTION.
--
-- ============================================================================================
-- WHAT RUNNING THIS CHANGES FOR THE OWNER
-- ============================================================================================
-- Nothing visible today: the Silvestri group already reads "Silvestri" everywhere, because the
-- stamped tier still had four voters and won. What it changes is the group's resilience — with the
-- stamp back, all five plans agree on WHEN the project was renamed, so no future comparison can
-- fall back to the legacy majority rule for this group. It is a repair to the evidence, not to a
-- symptom he can see.
--
-- ============================================================================================
-- THE AUDIT QUERY — run this FIRST, and again after. Read-only.
-- ============================================================================================
--   select coalesce(data->>'groupId', id) as grp,
--          count(*)                                                              as live_plans,
--          count(*) filter (where jsonb_typeof(data->'siteRenamedAt') = 'number') as stamped,
--          count(*) filter (where jsonb_typeof(data->'siteRenamedAt') = 'null')   as emptied,
--          max((data->>'siteRenamedAt')::bigint)                                  as group_stamp,
--          array_agg(distinct data->>'site')                                      as names
--     from public.sites
--    where deleted_at is null
--    group by 1
--   having count(*) filter (where jsonb_typeof(data->'siteRenamedAt') = 'number') > 0
--      and count(*) filter (where public.rename_stamp(data->'siteRenamedAt') is null) > 0;
--
--   -- 2026-09-10: returns exactly one row — smrp1wrgg6u5, 5 live plans, 4 stamped, 1 emptied,
--   -- group_stamp 1785525795307, names {Silvestri}. If it returns MORE than that when you come to
--   -- run this, something has erased another stamp since — stop and find out what, because the
--   -- guard was supposed to make that impossible.
--
-- ============================================================================================
-- THE REPAIR. Scoped by PROPERTY, never by a hardcoded id list: it only ever writes a row whose
-- OWN GROUP already holds the stamp being written, so it cannot invent one, and it is idempotent
-- (a second run matches nothing). `updated_at` is deliberately NOT bumped — it is the CAS input
-- the client's optimistic-concurrency layer compares against, and moving it would hand every open
-- tab a spurious "changed in another session" conflict on a field the user never touched (the same
-- reasoning db/sites_county_normalize.sql gives for its own backfill).
-- ============================================================================================

-- begin;   -- ⛔ uncomment the transaction and the statement below only when authorised to run this.
--
-- with group_stamp as (
--   select coalesce(data->>'groupId', id) as grp,
--          max(public.rename_stamp(data->'siteRenamedAt')) as at
--     from public.sites
--    where deleted_at is null
--    group by 1
--   having max(public.rename_stamp(data->'siteRenamedAt')) is not null
-- )
-- update public.sites s
--    set data = jsonb_set(s.data, '{siteRenamedAt}', to_jsonb(g.at), true)
--   from group_stamp g
--  where coalesce(s.data->>'groupId', s.id) = g.grp
--    and s.deleted_at is null
--    and public.rename_stamp(s.data->'siteRenamedAt') is null;
--
-- commit;
--
-- Expected on 2026-09-10: UPDATE 1.
--
-- ⛔ THE TRIGGER DOES NOT BLOCK THIS, and that is by design, not an oversight: this write carries a
-- real numeric stamp, so `sites_preserve_rename_stamp` passes it straight through. Verify by
-- re-running the audit query — it must come back empty.
