-- B1777120 (NEW-1, 2026-09-18) -- split planar_data's single whole-account JSON blob into
-- one row per schedule (public.schedules) plus one small per-account index row
-- (public.schedule_account_index). See BACKLOG.md B1777120 for the full brief and the
-- ALREADY-MEASURED numbers (production project lyeqzkuiwngunutlkkmi): one planar_data row,
-- key 'hs-v1', ~419KB, 10 projects, ~926 tasks, every save today rewrites the whole thing,
-- so an edit in one schedule contends with an edit in any OTHER schedule for no reason a
-- person would recognise.
--
-- THIS FILE IS ADDITIVE ONLY. It creates two new tables and does not touch planar_data,
-- planar_history, or planar_suggestions in any way -- the blob stays authoritative (see
-- schedules_decompose_recompose.sql for the dual-write/reverse-path functions, and
-- BACKLOG.md B1777120 for why the authority flip is explicitly NOT part of this change --
-- this item ships dual-read, dual-write, the idempotent migration and the exercised reverse
-- path, and stops before the flip).
--
-- SHAPE DECISIONS, recorded here so a future session does not re-derive or re-litigate them:
--
-- 1. schedules.data holds the COMPLETE, UNTOUCHED project object exactly as it lived at
--    value->'projects'->pid in the old blob (id/name/linkedSiteId/linkedSiteName included,
--    not stripped). name/linked_site_id/linked_site_name are ALSO promoted to real columns,
--    as DENORMALIZED, kept-in-sync-at-write-time copies for indexing/filtering -- `data`
--    stays the single source of truth for content. This is a deliberate deviation from a
--    literal reading of the dispatch's "data (its tasks)" phrasing: stripping the promoted
--    fields out of `data` would make the reverse (recompose) path a nontrivial per-field
--    reconstruction (it would have to know whether a null-valued key was PRESENT or ABSENT
--    in the original, since jsonb equality is key-presence-sensitive -- e.g. a schedule with
--    no linked site has NO `linkedSiteId` key at all, not a null one) for a few dozen bytes
--    of saved space per row. Keeping `data` whole makes recompose a single jsonb_object_agg
--    and the reverse-path proof exact by construction. Flagged explicitly per this repo's
--    "say so if you disagree" convention -- see BACKLOG.md B1777120.
--
-- 2. schedules.id is `generated by default as identity`, NOT `generated always` -- so the
--    migration can INSERT the legacy pid explicitly (keeping every existing external
--    reference -- schedule_account_index.last_active_by_site values, Shell.jsx's
--    scheduleProjectId, planar_suggestions.project_id -- valid with no translation table)
--    and the sequence is then restarted past the observed max pid. A brand-new schedule
--    (post-flip) gets its id from Postgres at INSERT time -- an atomic allocation, never a
--    client-computed counter two tabs could race on. This directly answers the dispatch's
--    "ID allocation" question for nPid: allocate from a real database sequence (the identity
--    column's own backing sequence), because creating a schedule is already a network
--    round-trip in the current code (addProject already calls window.storage.set right
--    after minting nPid) and a schedule's pid is a real, externally-referenced identity,
--    unlike a task's positional `id` (see point 3 below) -- a random-suffix client-generated
--    id was the other option named in the brief and was rejected here because it would
--    change the visible id format for a value multiple OTHER tables/call sites already
--    reference as a small integer, for no benefit a sequence doesn't already give.
--
-- 3. nTid (the per-project next-task-id hint) is NOT promoted to a database-enforced
--    allocator, and does not move into schedule_account_index despite the dispatch's own
--    "THE SHAPE TO BUILD" bullet listing it there. AUDIT-FIRST finding, recorded because it
--    contradicts that bullet: task IDENTITY in this document has ALREADY been solved by a
--    fix that shipped ONE DAY before this dispatch was written (NEW-1, owner report
--    2026-09-17, public/sequence/index.html's `_sid`/`_mintTaskSid` -- a permanent,
--    client-minted, collision-proof identity, already the merge/diff key in mergeCloudDoc,
--    unrelated to and unaffected by this migration). The numeric task `id` is a pure
--    POSITIONAL/display value, unconditionally reassigned 1..N by renumberTasks on every
--    structural edit -- nTid only ever seeds the value passed into mkt() before that
--    immediate renumber overwrites it, so it cannot produce a genuine identity collision
--    even when stale (the code's own comment already says so: "nTid can go stale ... Always
--    allocate above every existing id"). Putting nTid in the ACCOUNT-WIDE index row, as the
--    dispatch's shape bullet describes, would reintroduce exactly the cross-schedule
--    contention this migration exists to remove (every task add, in any schedule, would
--    touch one shared row) -- which is what the dispatch's OWN "design points" section then
--    separately instructs against ("Do NOT leave them in a row that two tabs race on"). This
--    file resolves that tension in favor of the explicit instruction: nTid is carried in
--    `schedule_account_index.n_tid` ONLY as an inert, informational copy during the
--    dual-write window (so a rollback to the old blob shape reconstructs byte-exactly); the
--    field that will actually matter post-flip is per-schedule (already inside
--    `schedules.data->>'nTid'`, unchanged from what already ships in `data` today), not a
--    new database-enforced allocator -- because none is needed. See BACKLOG.md B1777120 for
--    the full reasoning.
--
-- Idempotent (create table/policy/trigger all guarded); safe to re-run.

begin;

create table if not exists public.schedule_account_index (
  user_id              uuid primary key references auth.users(id) default auth.uid(),
  team_id              uuid references public.teams(id),
  n_pid                integer not null default 1,
  n_tid                jsonb not null default '{}'::jsonb,
  last_active_by_site  jsonb not null default '{}'::jsonb,
  settings             jsonb not null default '{}'::jsonb,
  migration_flags      jsonb not null default '{}'::jsonb,
  rev                  bigint not null default 0,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on table public.schedule_account_index is
  'B1777120 -- one row per owner: the account-wide facts that used to live at the TOP LEVEL of '
  'the single planar_data (key=hs-v1) blob -- nPid/nTid/lastActiveBySite/settings/the _v6.._v9 '
  '(+ any future) migration flags. Scaffolding for the Schedule per-row normalization; planar_data '
  'stays authoritative until BACKLOG.md B1777120''s authority-flip step ships. See '
  'schedules_normalization.sql''s own header for the nTid placement decision.';

alter table public.schedule_account_index enable row level security;
revoke all on public.schedule_account_index from anon;
grant select, insert, update on public.schedule_account_index to authenticated;

drop policy if exists "select own schedule index" on public.schedule_account_index;
create policy "select own schedule index" on public.schedule_account_index
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "insert own schedule index" on public.schedule_account_index;
create policy "insert own schedule index" on public.schedule_account_index
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "update own schedule index" on public.schedule_account_index;
create policy "update own schedule index" on public.schedule_account_index
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.schedule_account_index_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists schedule_account_index_touch on public.schedule_account_index;
create trigger schedule_account_index_touch before update on public.schedule_account_index
  for each row execute function public.schedule_account_index_touch_updated_at();


create table if not exists public.schedules (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references auth.users(id) default auth.uid(),
  team_id           uuid references public.teams(id),
  linked_site_id    text,
  linked_site_name  text,
  name              text not null,
  data              jsonb not null default '{}'::jsonb,
  rev               bigint not null default 0,
  deleted_at        timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table public.schedules is
  'B1777120 -- one row per Scheduler schedule (was value->''projects''->pid inside the single '
  'planar_data blob). `data` holds the COMPLETE original project object untouched (id/name/'
  'linkedSiteId/linkedSiteName included) -- name/linked_site_id/linked_site_name are ALSO '
  'promoted to real columns as denormalized, kept-in-sync copies for indexing; `data` is the '
  'source of truth for content, not the promoted columns. Soft-delete only (deleted_at), never a '
  'hard DELETE for ordinary removal, matching this repo''s TOMBSTONE-DELETES convention. `rev` is '
  'a fresh per-SCHEDULE optimistic-concurrency token (see schedules_version_monotonic_guard.sql) '
  '-- NOT a copy of the old document-wide __rev, which had no per-schedule meaning. `id` is '
  '`generated by default as identity`, not `generated always`, so the migration can seed it from '
  'the legacy pid and every existing external reference to that pid stays valid unchanged -- see '
  'this file''s own header, point 2.';

create index if not exists schedules_user_id_idx on public.schedules(user_id) where deleted_at is null;
create index if not exists schedules_linked_site_id_idx on public.schedules(linked_site_id) where deleted_at is null;

alter table public.schedules enable row level security;
revoke all on public.schedules from anon;
grant select, insert, update on public.schedules to authenticated;

drop policy if exists "select own schedule" on public.schedules;
create policy "select own schedule" on public.schedules
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "insert own schedule" on public.schedules;
create policy "insert own schedule" on public.schedules
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "update own schedule" on public.schedules;
create policy "update own schedule" on public.schedules
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.schedules_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists schedules_touch on public.schedules;
create trigger schedules_touch before update on public.schedules
  for each row execute function public.schedules_touch_updated_at();

commit;

-- Verification (run after):
--   select count(*) from pg_tables where schemaname='public' and tablename in ('schedules','schedule_account_index');
--   -- must be 2.
