import { openSignedIn } from "./lib/signedInSession.mjs";
import { assertMeasurable } from "./lib/tabTiming.mjs";
const s = await openSignedIn({ base: "https://planyr.io" });
const { page } = s;
await assertMeasurable(page, "tmp-b01-a");
console.log("build", JSON.stringify(s.build), s.proof.email);
const prefs = () => page.evaluate(async () => { const u=(await window.pfSupabase.auth.getUser()).data.user; const r=await window.pfSupabase.from("profiles").select("prefs").eq("id",u.id); return JSON.stringify(r.data||r.error); });
console.log("prefs0", await prefs());
await page.waitForTimeout(2000);
await page.screenshot({path:"/tmp/b01-a.png"});
console.log(await page.evaluate(()=>[...document.querySelectorAll("[data-testid]")].map(e=>e.dataset.testid).slice(0,60).join(",")));
await s.close();
