import { openSignedIn } from "./lib/signedInSession.mjs";
import { assertMeasurable } from "./lib/tabTiming.mjs";
const s = await openSignedIn({ base:"https://planyr.io" });
const p = s.page;
console.log("build", JSON.stringify(s.build), s.proof.email);
await assertMeasurable(p,"tmp-b02-a");
await p.locator('[data-testid="module-tab-notes"]:visible').first().click();
await p.waitForTimeout(4000);
console.log(await p.evaluate(()=>[...document.querySelectorAll('[data-testid]')].map(e=>e.dataset.testid).filter(t=>/note/i.test(t)).slice(0,60).join(",")));
console.log(await p.evaluate(()=>document.body.innerText.slice(0,800)));
await p.screenshot({path:"/tmp/claude-0/-home-user-planyr/db5c0953-cf9e-5605-a866-2b8c4145b56f/scratchpad/b02a.png"});
await s.close();
